import "./globals.css";
import AppToaster from "@/components/providers/Toaster";
import Footer from "@/components/ui/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppToaster />
        {children}
        {/* footer */}
     <Footer/>
     
      </body>
    </html>
  );
}
