import "./globals.css";
import AppToaster from "@/components/providers/Toaster";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppToaster />
        {children}
      </body>
    </html>
  );
}
